# This is a basic workflow that is manually triggered

name: AlmaLinux Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: almalinux:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: kenchan0130/actions-system-info@master
      id: system-info
      
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "${{ steps.system-info.outputs.cpu-core }}"
        echo "${{ steps.system-info.outputs.cpu-model }}"
        echo "${{ steps.system-info.outputs.hostname }}"
        echo "${{ steps.system-info.outputs.kernel-release }}"
        echo "${{ steps.system-info.outputs.kernel-version }}"
        echo "${{ steps.system-info.outputs.name }}"
        echo "${{ steps.system-info.outputs.platform }}"
        echo "${{ steps.system-info.outputs.release }}"
        echo "${{ steps.system-info.outputs.totalmem }}"
        
