name: build win32
on:
  workflow_dispatch:

env:
  WXWIDGETS_VER: 3.2.6
  
jobs:
  build-win32:
    runs-on: windows-2022

    steps:

    - uses: kenchan0130/actions-system-info@master
      id: system-info

    - name: Install Dependencies
      run: |
        # iwr -outf mingw.zip https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.7-12.0.0-msvcrt-r3/winlibs-i686-posix-dwarf-gcc-14.2.0-mingw-w64msvcrt-12.0.0-r3.zip
        # unzip mingw.zip
        cmake --version
        git --version

